
export const metadata = {
  title: 'ProductList Create Next App',
  description: 'Generated by create next app',
}

export default function productListPage(params) {
  return(
    <h2>productListPage</h2>
  )
};
