
export const metadata = {
  title: 'Pages Create Next App',
  description: 'Generated by create next app',
}
export default function pagesPage(params) {
  return (
      <h2>
        pages
      </h2>
  )
};
